# Generated by Django 4.0.4 on 2022-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductrelation',
            name='bucket',
            field=models.BooleanField(default=False),
        ),
    ]
