# Generated by Django 4.0.4 on 2022-05-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_image_imagerelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=255)),
                ('miniature', models.CharField(max_length=255)),
                ('preview', models.CharField(max_length=255)),
                ('original_width', models.IntegerField()),
                ('original_height', models.IntegerField()),
                ('miniature_width', models.IntegerField()),
                ('miniature_height', models.IntegerField()),
                ('preview_width', models.IntegerField()),
                ('preview_height', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='imagerelation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.imageobject'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
