# Generated by Django 4.0.4 on 2022-05-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_imageobject_alter_imagerelation_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageobject',
            name='img_miniature',
            field=models.ImageField(default='default.svg', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imageobject',
            name='img_original',
            field=models.ImageField(default='default.svg', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imageobject',
            name='img_preview',
            field=models.ImageField(default='default.svg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
