# Generated by Django 4.0.4 on 2022-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_imageobject_img_miniature_imageobject_img_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageobject',
            name='img_miniature',
        ),
        migrations.RemoveField(
            model_name='imageobject',
            name='img_original',
        ),
        migrations.RemoveField(
            model_name='imageobject',
            name='img_preview',
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='miniature',
            field=models.ImageField(default='default.svg', upload_to='../media'),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='original',
            field=models.ImageField(default='default.svg', upload_to='../media'),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='preview',
            field=models.ImageField(default='default.svg', upload_to='../media'),
        ),
    ]
