# Generated by Django 4.0.4 on 2022-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_imageobject_img_miniature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageobject',
            name='miniature',
            field=models.ImageField(default='default.svg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='original',
            field=models.ImageField(default='default.svg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='preview',
            field=models.ImageField(default='default.svg', upload_to='media/'),
        ),
    ]
