# Generated by Django 4.0.4 on 2022-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_imageobject_miniature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageobject',
            name='img_miniature',
            field=models.ImageField(default='default.svg', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imageobject',
            name='img_original',
            field=models.ImageField(default='default.svg', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imageobject',
            name='img_preview',
            field=models.ImageField(default='default.svg', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='miniature',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='original',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='preview',
            field=models.CharField(max_length=255),
        ),
    ]
