# Generated by Django 4.0.4 on 2022-06-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_imageobject_img_miniature_imageobject_img_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='img_miniature',
            field=models.ImageField(default='default.svg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='img_original',
            field=models.ImageField(default='default.svg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='img_preview',
            field=models.ImageField(default='default.svg', upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='ImageRelation',
        ),
        migrations.AddField(
            model_name='imageproductrelation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.imageobject'),
        ),
        migrations.AddField(
            model_name='imageproductrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
